### ISSUE TITLE
Heart fat? Does it make any sense?

### ISSUE THREAD

**Issue by Ojami** [tarolangner/ukb_mimir#1]
Hi Taro,

Thanks for this great toolbox! I have a (kind of silly!) question: is it possible to estimae heart fat (I've seen LV mass estimation elsewhere) from neck-to-knee or other modalities available on UKBB? 

Thanks/Oveis

**Comment by tarolangner** [comment]
Hi Oveis,

that is an interesting question actually. I think technically it should be possible to get a rough estimate with the same methodology, but first we would need training data and currently I am not aware of any existing reference values for heart fat in UK Biobank.

Some of the measurements of visceral adipose tissue do include areas around the heart however, and in the saliency maps we can see that the network is able to target them.

**Comment by Ojami** [comment]
Thanks for your thoughts on this. Do you think it's possible to find a _complementary approach_ for this matter? E.g. one could estimate this from total body fat - (adipos + liver fat). If this is possible, we technically won't need to train a new net for this purpose.

Best/Oveis

**Comment by tarolangner** [comment]
You could certainly get many related variables from the system, but whether a formula like that could accurately estimate heart fat is another question. I am frankly out of my depth on this and can only recommend studying the medical literature to see if any such formulas have been proposed before. 

The closest my own work has come to this would be a comparison of visceral adipose tissue (VAT) measurements. UK Biobank offers these measurements either from DXA (field 23289) or by an MRI-based technique developed by the company AMRA Medical  (field 22407). You can see the difference here:
[DXA VAT saliency](https://github.com/tarolangner/mri-biometry/blob/master/supplementary_material/biometry_results/saliency/23289_DxaVatVolume.png)
[MRI VAT saliency](https://github.com/tarolangner/mri-biometry/blob/master/supplementary_material/biometry_results/saliency/22407_MriVatVolume.png)

The DXA measurement examines a smaller region of interest, spanning 20% of the range between tailbone and base of the skull. The MRI-based measurements by AMRA range up to a higher location along the thoracic spine, including parts of the heart. Perhaps calculating field 23289 - field 22407 could capture part of this difference, but it would necessarily be confounded by many other factors too.

**Comment by Ojami** [comment]
That's a great suggestion Taro, I'll definitely check this!
Unfortunately I couldn't find much in the literature, and seems no one has considered this so far (AFIK).

Again, appreciate your thoughts on this!

Best/Oveis
